### ISSUE TITLE
Does not work with `gatsby-plugin-remove-fingerprints` ❗

### ISSUE THREAD

**Issue by jon-sully** [netlify/gatsby-plugin-netlify#126]
Greetings team 👋 

I recently opened up https://answers.netlify.com/t/cdn-site-content-not-updating-after-gatsby-upload-build/56146/1 after running into some no-fun caching issues on my Gatsby site. After digging into the rabbit hole (as noted in the thread), the long-cache-headers strategy this plugin employs clashes with [`gatsby-plugin-remove-fingerprints`](https://www.gatsbyjs.com/plugins/gatsby-plugin-remove-fingerprints/) — long cache-headers for Gatsby files with no fingerprints makes for a bad time when subsequent builds produce the same named (but not fingerprinted) files 😅 

Just wanted to recommend adding a note of incompatibility in the README of this project as to maybe help other folks in the future 🙂

**Comment by ascorbic** [comment]
Yes, that is a good point. We have talked out whether this plugin should offer the option of either doing the remove-fingerprints or the long cache approach, because they are mutually exclusive

**Comment by wahidshafique** [comment]
I also was cross-linked from here https://answers.netlify.com/t/is-gatsby-plugin-remove-fingerprints-still-required/73042 and given that the plugin repo has all but disappeared, I think it makes sense for the netlify plugin to take up the mantle
