### ISSUE TITLE
Remove script preloading

### ISSUE THREAD

**Issue by ascorbic** [netlify/gatsby-plugin-netlify#127]
Gatsby 4.14 [removes most preloading of assets](https://www.gatsbyjs.com/docs/reference/release-notes/v4.14/#improvements-in-image-and-font-loading-times), because it turns out that it was affecting performance by interfering with the loading of more important assets like images. As well as the changes in Gatsby core, the update also removed all preload header handling [from the Gatsby Cloud plugin](https://github.com/gatsbyjs/gatsby/pull/35408/files#diff-08f569cd944faef1cab1a4193f2e26af6942cb59fbd8ad028b2d895c7afbadbc). We should do the same.

**Comment by mwskwong** [comment]
Agree. BTW, if I'm not mistaken, it is equivalent to setting `mergeLinkHeaders` to `false`. If that's the case, all we have to do is change the default value of `mergeLinkHeaders`

**Comment by ascorbic** [comment]
Effectively yes, but as it seems like it's a footgun it's better if we remove it entirely.
