### ISSUE TITLE
[Bug]: Gatsby Functions is skipped even if they exists

### ISSUE THREAD

**Issue by sjelfull** [netlify/gatsby-plugin-netlify#138]
**Summary**
I have a vanilla install of Gatsby + one Gatsby function. I installed to support Gatsby on Netlify.

Before upgrading to the newest version of `gatsby-plugin-netlify` it would detect functions as expected.

After upgrading, it skips building Gatsby functions.

**Steps to reproduce**
1. Pull down reproduction [repro-gatsby-netlify-functions-plugin](https://github.com/sjelfull/repro-gatsby-netlify-functions-plugin)
2. Deploy to Netlify
3. See message `Skipping Gatsby Functions and SSR/DSG support because gatsby-plugin-netlify reported that this site does not use them.`

**Plugin version**
5.0.0

**Comment by orinokai** [comment]
Closing as dup of https://github.com/netlify/netlify-plugin-gatsby/issues/385
