### ISSUE TITLE
Add support for Gatsby V5

### ISSUE THREAD

**Issue by gdams** [netlify/gatsby-plugin-netlify#195]
Now that Gatsby 5.0.0 is available, it would be good if this plugin could be updated to avoid the following warning:

```output
warn Plugin gatsby-plugin-netlify is not compatible with your gatsby version 5.0.0 - It requires gatsby@^4.0.0
```

Thanks, let me know if I can do anything to help?

**Comment by browniebroke** [comment]
I've given this a stab in #196 

You can try it out on your site by replacing the version in your `package.json`:

```json
{
  ...
  "dependencies": {
    ...
    "gatsby-plugin-netlify": "github:browniebroke/gatsby-plugin-netlify#gatsby-v5",
    ...
  }
}
```

**Comment by browniebroke** [comment]
Although it looks like renovate auto-updated in https://github.com/netlify/gatsby-plugin-netlify/pull/198

Probably needs a new release

**Comment by browniebroke** [comment]
Gatsby v5 needs node >= 18 so if this plugin only supports Gatsby 5, we should bump the minimum node version.

**Comment by bobmatyas** [comment]
Is a new version of this going to be released soon? Right now it's blocking upgrade to Gatsby v5.

**Comment by ZTKlein** [comment]
@bobmatyas for a temporary fix if you want to go ahead and work on the migration to gatsby 5 for your project, make use of NPM overrides or Yarn resolutions in your package.json; the plugin *should* still work fine with gatsby 5.
It should look something like this if you're using NPM:
```json
"overrides": {
  "gatsby-plugin-netlify": {
    "gatsby": "^5.0.0"
  }
}
```
If you're using Yarn:
```json
"resolutions": {
  "gatsby-plugin-netlify/gatsby": "^5.0.0"
}
```
I might be mistaken on the resolutions syntax, as I don't really use Yarn. Once this is added to your package.json, it might be necessary to delete your node_modules and reinstall. You'll get a warning when compiling that gatsby-plugin-netlify requires 4.0.0, but it won't actually prevent a build.

**Comment by gdams** [comment]
Looks like this was fixed in https://github.com/netlify/gatsby-plugin-netlify/commit/0467a34bcc4ab3c75445189390d374ced06c4d2d but no new release yet
