### ISSUE TITLE
Gatsby 4 support

### ISSUE THREAD

**Issue by RectoVersoDev** [netlify/gatsby-plugin-netlify#29]
Hello,

Got a build warning with Gatsby 4

`warn Plugin gatsby-plugin-netlify is not compatible with your gatsby version 4.0.0 - It requires gatsby@^3.0.0`

**Comment by broksonic21** [comment]
Any update on timing for this?

**Comment by Jukez17** [comment]
Version 3.14.0 of gatsby-plugin-netlify is working atm with gatsby v4

**Comment by oliverjohns** [comment]
<img width="567" alt="bild" src="https://user-images.githubusercontent.com/63138155/141680800-361b0d6a-1e01-48a8-ab29-0cd7387f3d62.png">
Im getting issues when trying to build my gatsby application:

`merge is not a function`

Think its due to netlify plugin not being compatible with latest gatsby? Any way to fix this?

**Comment by sniperyork** [comment]
I'm waiting for that support too

**Comment by dimitrisnl** [comment]
Bump. It would be great to have this, as it's the only thing blocking me from upgrading to Gatsby 4.

**Comment by Jukez17** [comment]
I have "gatsby-plugin-netlify": "^3.14.0" and updated to latest dependencies, everything is working fine now with gatsby v4 @oliverjohns  @sniperyork  @dimitrisnl and deploy on netlify was also successfull. Also I have these following dependencies at these versions: "netlify-cms-app": "^2.15.59", , gatsby-plugin-netlify-cms": "^6.1.0"

**Comment by ascorbic** [comment]
Hey. You can get v4 support in beta by installing `gatsby-plugin-netlify@next`. We should be releasing it as GA later this month

**Comment by oliverjohns** [comment]
> <img alt="bild" width="567" src="https://user-images.githubusercontent.com/63138155/141680800-361b0d6a-1e01-48a8-ab29-0cd7387f3d62.png">
> 
> Im getting issues when trying to build my gatsby application:
> `merge is not a function`
> 
> Think its due to netlify plugin not being compatible with latest gatsby? Any way to fix this?

This issue was not caused by gatsby-plugin-netlify, so pardon me writing here. Just wanted to clarify that the issue was with Formik and their old version of deepmerge.

**Comment by dfpera** [comment]
@ascorbic is the plan still to release v4 support as GA this week? Thanks in advance.

**Comment by chungsi** [comment]
Any news for an updated release date? 🤔

**Comment by RectoVersoDev** [comment]
Hi, any news for the stable v4 release of the plugin ?

**Comment by ascorbic** [comment]
Hello all. Thanks for your patience. Version 4 is now live.
