### ISSUE TITLE
Does this plugin add the correct Gatsby caching rules?

### ISSUE THREAD

**Issue by laurenskling** [netlify/gatsby-plugin-netlify#30]
I'm struggling everytime with `gatsby-plugin-offline` service workers on netlify. There are many a times I get stuck in service workers trying to add broken staticQuery data and my website crashing (before it can update the service worker i guess)

I'm getting the feeling we are not using the correct caching rules Gatsby set out:
https://www.gatsbyjs.com/docs/caching/
mainly about app data and page-data.json

This is something I would assume this plugin does for me, right?

**Comment by keegankb93** [comment]
Hello from a year later. The answer to your question is a sound, "No, this plugin is not following the correct caching headers as set out by Gatsby. You should add these headers i.e. app-data and page-data to your plugin options in the config. I don't know why this plugin doesn't.

**Comment by ericapisani** [comment]
Hi folks,

The cache headers that Gatsby advises for page data and app data are the same as the default cache control headers that Netlify returns in the response (`cache-control: public, max-age=0, must-revalidate`)

The Gatsby [demo site](https://netlify-plugin-gatsby-demo.netlify.app/page-data/index/page-data.json) that we have for the `netlify-plugin-gatsby` project shows that those headers are being returned as expected. Does your project also have [netlify-plugin-gatsby](https://github.com/netlify/netlify-plugin-gatsby) installed?

If this is still an ongoing issue, please let us know, ideally along with a minimal reproduction project and steps to reproduce.

**Comment by laurenskling** [comment]
Hello @ericapisani , thanks for your response.
I used to struggle a lot with the service worker. The service worker should not be cached and I think it did.
https://www.gatsbyjs.com/docs/caching/#javascript-and-css
I'm by far no expert in service workers, so I cannot be certain if it was caching or some other installation issue.
I cannot give you an example right now since I removed all my `gatsby-plugin-offline` installs a while ago, since they only resulted trouble.

**Comment by ericapisani** [comment]
@laurenskling Ah ok, that's good information to have, thanks for letting us know! We'll keep an eye out for any similar issues related to the use of this (and other service worker) plugins and take further steps if we begin to notice a pattern emerge
