### ISSUE TITLE
What's the LICENSE for this project?

### ISSUE THREAD

**Issue by sweethuman** [netlify/gatsby-plugin-netlify#50]
There doesn't seem to be a license file, or a license mentioned. Is it MIT?

**Comment by ascorbic** [comment]
Hey. Yes, it's MIT. It's just [a line in the `package.json`](https://github.com/netlify/gatsby-plugin-netlify/blob/main/package.json#L53) right now, so thanks for the prompt. I'll see about getting a proper LICENSE file added
