### ISSUE TITLE
SSR and DSG not working

### ISSUE THREAD

**Issue by alexjidras** [netlify/gatsby-plugin-netlify#67]
Steps to reproduce:
1) Create a project from official starter https://github.com/gatsbyjs/gatsby-starter-rendering-modes
`npx gatsby new gatsby-starter-rendering-modes https://github.com/gatsbyjs/gatsby-starter-rendering-modes`
2) add 'gatsby-plugin-netlify'
`yarn add -D gatsby-plugin-netlify`
3) add plugin to gatsby
```
// gatsby-config.js
module.exports = {
    plugins: ['gatsby-plugin-netlify'],
}
```
4) push code to github
5) deploy to netlify

package.json

```
{
  "name": "gatsby-starter-rendering-modes",
  "private": true,
  "version": "1.0.0",
  "description": "A Gatsby starter to demonstrate new rendering modes in Gatsby 4",
  "main": "index.js",
  "scripts": {
    "start": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve",
    "clean": "gatsby clean"
  },
  "author": "Brent Jackson <jxnblk@gmail.com>",
  "license": "0BSD",
  "dependencies": {
    "gatsby": "^4.0.2",
    "node-fetch": "^2.6.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "gatsby-plugin-netlify": "^4.0.0"
  }
}
```

Result:

https://awesome-liskov-661da1.netlify.app/ 
![image](https://user-images.githubusercontent.com/33176605/151378322-5e9d5439-357e-41ea-a260-ad110f887dec.png)
https://awesome-liskov-661da1.netlify.app/dsg ![image](https://user-images.githubusercontent.com/33176605/151377568-b42d44c4-06bd-406d-a168-7b9f5493c9c3.png)
https://awesome-liskov-661da1.netlify.app/ssr ![image](https://user-images.githubusercontent.com/33176605/151377633-9675e988-f59f-42c6-83a4-b3eda32111d3.png)

**Comment by Simply007** [comment]
I had the same problem.

Then I have added Gatsby essential plugin manually through the Netlify UI and I am getting the error:

```
A Netlify Function failed to require one of its dependencies.
11:06:57 AM:   Please make sure it is present in the site's top-level "package.json"

Cannot find module '../../../.cache/functions/manifest.json' from '/opt/build/repo/.netlify/functions-internal/__api
```

And my build is failing. not sure it was a step forward to the solution or just a dead-end though.

**Comment by nickytonline** [comment]
Closing as the solution is to upgrade to the latest version of the Essential Gatsby Plugin.
